site_name: Tad Study
theme:
  name: material
  logo: assets/logo/cat_white.png
  text: Noto Serif Medium
  code: Roboto Mono Medium
  highlightjs: true
  hljs_style: github
  hljs_style_dark: github-dark
  palette:
  - scheme: default
    primary: indigo
    accent: pink
    toggle:
      icon: material/brightness-4
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: pink
    toggle:
      icon: material/brightness-7
      name: Switch to light mode
  features:
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.instant
    - navigation.footer
    - navigation.tracking

plugins:
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/

nav:
  ########################################################################################################################
  - Study: index.md
  ########################################################################################################################
  - Hẳng Số:
    - Vật Lý: Physics/physics-constant.md
    - Toán II: Math2/math-2-mathematical-constant.md
  ########################################################################################################################
  - Toán Học Cơ Bản:
    - ❖ Chung:
      - Toán Cơ Bản: Math/math.md
      - Tập hợp số: Math/math-phan-so.md
      - Số Nguyên Tố: Math/math-prime-number.md
      - Ước & Bội: Math/math-divisor-and-multiple.md
    - ❖ Số Học:
      - Số Học: Math/math-numberic-overview.md
      - Hẳng Đẳng Thức: Math/math-identity-overview.md
    - ❖ Hình Học:
      - Hình Học Cơ Bản: Math/math-geometry-overview.md
  - Toán Học Cao Cấp:
    - Tổng Quan: Math2/math-2-overview.md
    - Công Thức Euler: Math2/math-2-euler.md
  ########################################################################################################################
  - Vật Lý:
    - Overview: Physics/physics-overview.md
    - ❖ Cơ Học:
      - Lực đẩy Archimedes: Physics/physics-mechanics-luc-day-archimedes.md
      - 3 Newton's Laws: Physics/physics-mechanics-3-newton-laws-of-motion.md
    - Speed of light: Physics/physics-speed-of-light.md
    - Fourier: Physics/physics-fourier.md
  ########################################################################################################################
  - Hoá Học:
    - Overview: Chemistry/chemistry-overview.md
  ########################################################################################################################
  - Lịch Sử:
    - ❖ Lịch Sử VN:
      - Overview: History_VN/vn-history-overview.md
      - VN các thời kỳ: History_VN/vn-history-tong-quan-cac-thoi-ky.md
      - Thời Tiền Sử: History_VN/vn-history-thoi-ky-tien-su.md
      - Thời Cổ Đại: History_VN/vn-history-thuong-co-thoi-dai.md
      - ❖ Truyện Dân Gian:
        - Truyền Thuyết Con Rồng Cháu Tiên: History_VN/vn-history-truyen-thuyet-con-rong-chau-tien.md
  ########################################################################################################################
  - Triết Học:
    - Overview: Philosophy/philosophy-overview.md
    - ❖ Stoicism:
      - Overview: Philosophy/stoicism-overview.md
    - ❖ Triết Học cá nhân:
      - Overview: Philosophy/philosophy-personalized-philosophy.md
      - Pokemon: Philosophy/philosophy-pokemon.md
  ########################################################################################################################
  - Tiếng Anh:
    - ❖ Grammaly:
      - Từ và Câu: English/english-words-and-sentences.md
    - ❖ Reading:
      - An Introduction to Film Sound: English/english-an-introduction-to-film-sound.md
      - How to find your way out of a food desert: English/english-how-to-find-your-way-out-of-a-food-desert.md

extra_css:
  - assets/stylesheets/theme.css
  - https://unpkg.com/katex@0/dist/katex.min.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

extra_javascript:
  - assets/scripts/katex.js
  - assets/scripts/keyevent.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dothanhdathp
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/tad.zeila?locale=vi_VN
